In [1]:
###Load the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
import sklearn 
from sklearn.linear_model import LogisticRegression 

In [18]:
from sklearn.model_selection import train_test_split

In [32]:
from sklearn.metrics import accuracy_score

In [8]:
###Load the dataset

data=pd.read_csv(r'ChurnData.csv')

In [9]:
data

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [10]:
### Data Analysis

data.describe()

tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless    longmon  ...       pager  \
count  200.000000  200.000000  200.000000  200.00000  ...  200.000000   
mean     0.425000    0.705000    0.290000   11.78925  ...    0.275000   
std      0.495584    0.457187    0.454901    9.88725  ...    0.447635   
min      0.000000    0.000000    0.000000    1.10000  ...    0.000000   
25%      0.000000    0.000000    0.000000    5.53750  ...    0.000000   
50%      0.000000    1.000000    0.000000    8.25000  ...    0.000000   
75%      1.000000    1.000000    1.000000   14.30000  ...    1.000000   
max      1.000000    1.000000    1.000000   62.30000  ...    1.000000   

         internet   callwait      confer       ebill     loglong     logtoll  \
count  200.000000  200.00000  200.000000  200.000000  200.000000  200.000000   
mean     0.440000    0.45500    0.460000    0.440000    2.193285    3.229185   
std      0.497633    0.49922    0.499648    0.497633    0.731282    0.281019   
min      0.000000    0.00000    0.000000    0.000000    0.095000    1.749000   
25%      0.000000    0.00000    0.000000    0.000000    1.711750    3.226500   
50%      0.000000    0.00000    0.000000    0.000000    2.110000    3.240000   
75%      1.000000    1.00000    1.000000    1.000000    2.660000    3.240000   
max      1.000000    1.00000    1.000000    1.000000    4.132000    4.227000   

            lninc     custcat       churn  
count  200.000000  200.000000  200.000000  
mean     3.951015    2.475000    0.290000  
std      0.752553    1.079445    0.454901  
min      2.197000    1.000000    0.000000  
25%      3.434000    2.000000    0.000000  
50%      3.871000    2.000000    0.000000  
75%      4.382000    3.000000    1.000000  
max      7.419000    4.000000    1.000000  

[8 rows x 28 columns]

In [12]:
data.dtypes

tenure      float64
age         float64
address     float64
income      float64
ed          float64
employ      float64
equip       float64
callcard    float64
wireless    float64
longmon     float64
tollmon     float64
equipmon    float64
cardmon     float64
wiremon     float64
longten     float64
tollten     float64
cardten     float64
voice       float64
pager       float64
internet    float64
callwait    float64
confer      float64
ebill       float64
loglong     float64
logtoll     float64
lninc       float64
custcat     float64
churn       float64
dtype: object

In [13]:
### Data cleaning

data['churn']=data['churn'].astype('int')

In [16]:
data.dtypes

tenure      float64
age         float64
address     float64
income      float64
ed          float64
employ      float64
equip       float64
callcard    float64
wireless    float64
longmon     float64
tollmon     float64
equipmon    float64
cardmon     float64
wiremon     float64
longten     float64
tollten     float64
cardten     float64
voice       float64
pager       float64
internet    float64
callwait    float64
confer      float64
ebill       float64
loglong     float64
logtoll     float64
lninc       float64
custcat     float64
churn         int32
dtype: object

In [19]:
### Dividing the data to train and test

x=data.loc[:,'tenure':'custcat']
y=data['churn']


In [20]:
x.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  voice  pager  internet  callwait  confer  ebill  loglong  \
0     4.40  ...    1.0    1.0       0.0       1.0     1.0    0.0    1.482   
1     9.45  ...    0.0    0.0       0.0       0.0     0.0    0.0    2.246   
2     6.30  ...    0.0    0.0       0.0       0.0     1.0    0.0    1.841   
3     6.05  ...    1.0    1.0       1.0       1.0     1.0    1.0    1.800   
4     7.10  ...    1.0    0.0       0.0       1.0     1.0    0.0    1.960   

   logtoll  lninc  custcat  
0    3.033  4.913      4.0  
1    3.240  3.497      1.0  
2    3.240  3.401      3.0  
3    3.807  4.331      4.0  
4    3.091  4.382      3.0  

[5 rows x 27 columns]

In [21]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: churn, dtype: int32

In [22]:
test_size=0.30
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=test_size)

In [24]:
x_train.shape

(140, 27)

In [36]:
y_train.shape

(140,)

In [27]:
### Define the algorithm

log_obj=LogisticRegression()



In [28]:
### Train the model ie Model creation

log_obj.fit(x_train,y_train)

C:\Users\Elakk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
### Evaluate the model

y_pred=log_obj.predict(x_test)

In [30]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0])

In [37]:
### Check the probabilities

log_obj.predict_proba(x_test)

array([[9.78401704e-01, 2.15982962e-02],
       [9.16236870e-01, 8.37631300e-02],
       [9.99563349e-01, 4.36650521e-04],
       [6.94184249e-01, 3.05815751e-01],
       [2.71068091e-01, 7.28931909e-01],
       [8.61205414e-01, 1.38794586e-01],
       [8.47087937e-01, 1.52912063e-01],
       [5.00672349e-01, 4.99327651e-01],
       [4.01634474e-01, 5.98365526e-01],
       [9.75921129e-01, 2.40788709e-02],
       [5.45352824e-01, 4.54647176e-01],
       [9.88844552e-01, 1.11554477e-02],
       [5.51473634e-01, 4.48526366e-01],
       [9.61186413e-01, 3.88135865e-02],
       [9.75110888e-01, 2.48891116e-02],
       [5.32933871e-01, 4.67066129e-01],
       [1.60121224e-01, 8.39878776e-01],
       [5.41097417e-01, 4.58902583e-01],
       [8.09602819e-01, 1.90397181e-01],
       [6.46533010e-01, 3.53466990e-01],
       [2.49640691e-01, 7.50359309e-01],
       [8.12494435e-01, 1.87505565e-01],
       [9.88209330e-01, 1.17906698e-02],
       [9.86076801e-01, 1.39231991e-02],
       [9.765261

In [31]:
y_test

126    0
133    0
116    0
42     0
160    1
43     1
132    0
32     0
157    1
153    1
90     1
31     0
102    0
143    0
94     0
71     0
15     1
7      0
83     1
21     0
54     1
72     0
194    0
141    0
67     0
80     0
193    0
109    0
180    0
175    0
52     0
18     0
131    1
118    0
195    0
37     0
82     1
27     0
91     0
198    1
158    0
179    0
185    0
142    0
123    1
183    0
70     1
3      0
51     0
8      0
111    1
75     0
50     0
163    1
170    0
174    1
164    0
5      0
23     0
129    0
Name: churn, dtype: int32

In [34]:
accuracy_score(y_pred,y_test)

0.7833333333333333

In [35]:
### Here accuracy_score is 78% or it is nearer to 1,but this not enough to predict classification problems as it doesnt calculate sensitivity etc
### So now we need to go for confusion_matrix

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
confusion_matrix(y_pred,y_test)

array([[40,  9],
       [ 4,  7]], dtype=int64)

In [ ]:
### here TP=40, FP=9, FN=4, TN=7

In [40]:
from sklearn.metrics import classification_report

In [42]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.91      0.82      0.86        49
           1       0.44      0.64      0.52        11

    accuracy                           0.78        60
   macro avg       0.67      0.73      0.69        60
weighted avg       0.82      0.78      0.80        60



In [ ]:
### here support- no.of values, o= negative cases, 1= positive cases, f1-score=combination of Recall and Precision inorder to maintain the balance between them
### here we have 49 negative cases and 11 positive cases and total of 60 ie support.